<?php
  use ctubio\HKPProxy\Keyserver;
  use Proxy\Factory;
  use Symfony\Component\HttpFoundation\Request;
  $content = Factory::forward(Request::create('/haproxy'))->to(
      'http://'.Keyserver::getConfig()->hkp_load_balanced_addr.':'.Keyserver::getConfig()->hkp_load_balanced_port.'/haproxy'
    )->getContent();
  Keyserver::getConfig()->indent_strict_html = 0;
  echo str_replace('body { font-family: arial, helvetica, sans-serif; font-size: 12px; font-weight: normal; color: black; background: white;}',NULL,
    str_replace('h1 { font-size: x-large; margin-bottom: 0.5em;}',NULL,
    str_replace('h2 {  font-size: x-large; font-weight: bold; font-style: italic; color: #6020a0; margin-top: 0em; margin-bottom: 0em;}',NULL,
    str_replace('font-family: helvetica, arial;',NULL,
      preg_replace('/.*(<style type="text\/css">.*<\/style>).*$/s', '$1', $content
  )))));
  echo '<div><style type="text/css" scoped>td.noborder{font-size:16px!important;}table.tbl td{font-family: monospace;}table.tbl tr.active0 td, table.tbl tr.active1 td,table.tbl tr.active2 td,table.tbl tr.active3 td, table.tbl tr.active4 td,table.tbl tr.active8 td,table.tbl tr.active8 td,table.tbl tr.active9 td,table.tbl tr.maintain td,,table.tbl tr.backup2 td,table.tbl tr.backup3 td,,table.tbl tr.bakcup4 td,.pxname{font-family: monospace;font-size:13px!important;}table:first-of-type{float:right;}h2:last-of-type,hr,h3,td[align=left]{display:none;}</style>';
  echo str_replace('<h1><a href="http://www.haproxy.org/" style="text-decoration: none;">HAProxy</a></h1>', '<h2 style="float: left;">HAProxy Load Balancer statistics<br />Taken at '.date('Y-m-d H:m:s T').':</h2>',
    str_replace('Note: "NOLB"/"DRAIN" = UP with load-balancing disabled.',NULL,
    preg_replace('/.*<body>(.*)<\/body>.*$/s', '$1', $content
  )));
  echo '</div>';
?>
