      <h2>
        Extract a Key
      </h2>
      <form action="/pks/lookup" method="get">
        <p>
          Search String:
          <input name="search" size="45" value="" />
          <input type="submit" value="Do the search!" />
        </p>
        <table>
          <tr>
            <td>
              <input type="checkbox" name="fingerprint" checked="checked" />
              Show PGP fingerprints
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="index" />
              Show regular output
            </td>
          </tr>
          <tr>
            <td>
              <input type="checkbox" name="hash" />
              Show full-key hashes
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="vindex" checked="checked" />
              Show verbose output
            </td>
          </tr>
          <tr>
            <td>
              <input type="checkbox" name="options" value="mr" />
              Show machine readable output
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="get" />
              <span style="display:none;"> Download</span>
              <span> Show</span>
              ASCII-armored keys
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <input type="checkbox" name="exact" />
              Only return exact matches
            </td>
          </tr>
        </table>
        <script type="text/javascript">
          $(document).ready(function(){
            $('input[value="mr"]').change(function(){
              $('input[value="get"]').next()[$(this).is(':checked')?'show':'hide']();
              $('input[value="get"]').next().next()[$(this).is(':checked')?'hide':'show']();
            }).change();
          });
        </script>
      </form>
      <hr />
      <h2>
        Submit a Key
      </h2>
      <form action="/pks/add" method="post">
        <p>Enter ASCII-armored PGP key here:</p>
        <p>
        <textarea name="keytext" rows="21" cols="69"></textarea>
        </p>
        <p>
        <input type="reset" value="Clear" />
        <input type="submit" value="Submit this key to the keyserver!" />
        </p>
      </form>
      <hr />
      <h2>
        Remove a key
      </h2>
      <form action="/faq">
        <p>Search String:
        <input name="search" size="45" />
        <input type="submit" value="Remove my key!" />
        </p>
      </form>
