<?php
  use ctubio\HKPProxy\Keyserver;
  use ctubio\HKPProxy\Keyserver\Boinc;
  use Proxy\Factory;
  use Symfony\Component\HttpFoundation\Request;
  $content = Factory::forward(Request::create('/haproxy'))->to(
      'http://'.Keyserver::getConfig()->hkp_load_balanced_addr.':'.Keyserver::getConfig()->hkp_load_balanced_port.'/haproxy'
    )->getContent();
  Keyserver::getConfig()->indent_strict_html = 0;
  echo '<div id="haproxy">';
  echo str_replace('<h1><a href="http://www.haproxy.org/" style="text-decoration: none;">HAProxy</a></h1>', '<h2 style="margin-bottom:0px;">HAProxy Load Balancer statistics<br />Taken at '.date('Y-m-d H:i:s T').':</h2>',
    str_replace('Note: "NOLB"/"DRAIN" = UP with load-balancing disabled.',NULL,
    preg_replace('/.*<body>(.*)<\/body>.*$/s', '$1', $content
  )));
  echo '</div>';
?>
<?php if (!Keyserver::getConfig()->boinc_machines_addr) return; ?>
<br />
<h2>Berkeley Open Infrastructure for Network Computing statistics<br />Taken at <?php echo date('Y-m-d H:i:s T'); ?>:</h2>
<h3>Projects Summary:</h3>
<center><? # feel free to go to http://boinc.mundayweb.com and generate your own summary images. ?>
<img src="http://boinc.mundayweb.com/stats.php?userID=14891" /><br/>
<img src="http://boinc.mundayweb.com/stats.php?userID=14891&prj=1" />
<img src="http://boinc.mundayweb.com/teamStats.php?userID=14891&prj=1" /><br />
<img src="http://boinc.mundayweb.com/stats.php?userID=14891&prj=124" />
<img src="http://boinc.mundayweb.com/teamStats.php?userID=14891&prj=124" />
</center>
<h3>Current Workunits Assigned:</h3>
<?php echo new Boinc(); ?>