<h2>Index of /<a title="dump" href="/dump/">dump</a></h2>
<ul>
<?php foreach(glob(($prefix=realpath('dump')).'/*') as $dump):
  $dump = substr($dump, strlen($prefix)+1); ?>
<li><a title="<?php echo $dump; ?>" href="/dump/<?php echo $dump; ?>/"> <i><?php echo $dump; ?></i></a></li>
<?php endforeach; ?>
</ul>
<?php if (is_file($file=realpath('dump/current/README.txt')) and is_readable($file)): ?>
<h2>README of <a title="current" href="/dump/current/">current</a> keydump</h2>
<pre><?php echo htmlentities(file_get_contents($file)); ?></pre>
<?php else:?>
<h2>Oops!</h2>
<pre>Sorry but a new keydump just started right now, please come back in a few minutes.</pre>
<?php endif;?>
