<?php echo $this->getBlock('header'); ?>
    <title><?php echo $this->getConfig('html_title') ?></title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
  </head>
  <body>
    <div id="gnulinux-inside" style="position: absolute; top: 0px; right: 0px;">
      <a href="https://www.gnu.org/philosophy/#mission-statement">
        <img src="https://www.gnu.org/graphics/gnu-inside.png"
          alt="GNU/Linux Inside!" title="GNU/Linux Inside!" />
      </a>
    </div>
    <div id="content" style="width:640px;margin:0px auto;">
      <h1><?php echo $this->getConfig('html_title') ?></h1>
      <hr />
      <h2>
        <a id="extract" name="extract">Extract a Key</a>
      </h2>
      <form action="/pks/lookup" method="get">
        <p>
          Search String:
          <input name="search" size="45" value="" />
          <input type="submit" value="Search!" />
        </p>
        <table>
          <tr>
            <td>
              <input type="checkbox" name="fingerprint" checked="checked" />
              Show PGP fingerprints
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="vindex" checked="checked" />
              Show verbose output
            </td>
          </tr>
          <tr>
            <td>
              <input type="checkbox" name="hash" />
              Show full-key hashes
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="index" />
              Show regular output
            </td>
          </tr>
          <tr>
            <td>
              <input type="checkbox" name="options" value="mr" />
              Show machine readable output
            </td>
            <td>
            </td>
            <td>
              <input type="radio" name="op" value="get" />
              <span style="display:none;">Download</span>
              <span>Show</span>
              ASCII-armored keys
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <input type="checkbox" name="exact" />
              Only return exact matches
            </td>
          </tr>
        </table>
        <script type="text/javascript">
          $(document).ready(function(){
            $('input[value="mr"]').change(function(){
              $('input[value="get"]').next()[$(this).is(':checked')?'show':'hide']();
              $('input[value="get"]').next().next()[$(this).is(':checked')?'hide':'show']();
            }).change();
          });
        </script>
      </form>
      <hr />
      <h2>
      <a id="submit" name="submit">Submit a Key</a>
      </h2>
      <form action="/pks/add" method="post">
        <p>Enter ASCII-armored PGP key here:</p>
        <p>
        <textarea name="keytext" rows="21" cols="69"></textarea>
        </p>
        <p>
        <input type="reset" value="Clear" />
        <input type="submit" value="Submit this key to the keyserver!" />
        </p>
      </form>
      <hr />
      <h2>
        <a id="remove" name="remove">Remove a key</a>
      </h2>
      <form action="/doc/faq">
        <p>Search String:
        <input name="search" size="45" />
        <input type="submit" value="Remove my key!" />
        </p>
      </form>
<?php echo $this->getBlock('footer'); ?>
