language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6

git:
  submodules: false

before_install:
  - make
  - $(sed -e "s/^;\(hkp_addr\).*$/\1 = pgp.key-server.io/" <<< "$(cat etc/php-proxy-keyserver.ini)") > etc/php-proxy-keyserver.ini

script:
  - make test

after_success:
  - make coverage

notifications:
  email:
    on_success: never

