language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6

git:
  submodules: false

before_install:
  - sudo apt-get install sks -y -o Dpkg::Options::="--force-confdef"
  - echo "initstart=yes" | sudo tee /etc/default/sks
  - sudo ls -la /etc/sks/*
  - echo -e "hkp_port\x3A 11371\nhkp_address\x3A 127.0.0.1\nhostname\x3A none" | sudo tee /etc/sks/sksconf
  - sudo /etc/init.d/sks start
  - sudo cat /etc/sks/sksconf
  - curl http://127.0.0.1:11371/pks/lookup?op=stats
  - make

script:
  - make test

after_success:
  - make coverage

notifications:
  email:
    on_success: never
