language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6

git:
  submodules: false

before_install:
  - echo "initstart=yes" | sudo tee /etc/default/sks
  - sudo apt-get install sks -y -o Dpkg::Options::="--force-confdef"
  - sudo cat /var/lib/sks/sksconf
  - locate sksconf
  - make install

script:
  - make test

after_success:
  - make coverage

notifications:
  email:
    on_success: never
