language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6

git:
  submodules: false

before_install:
  - sudo apt-get install sks
  - make install

script:
  - make test

after_success:
  - make coverage

notifications:
  email:
    on_success: never
