language: php

branches:
  only:
    - master
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit -c test

notifications:
  email:
    on_success: never
