language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6

git:
  submodules: false

before_install:
  - sudo apt-get install sks -y -o Dpkg::Options::="--force-confdef"
  - echo "initstart=yes" | sudo tee /etc/default/sks
  - echo "hkp_address: 127.0.0.1" | sudo tee -a /etc/sks/sksconf
  - echo "hostname: localhost" | seed tee -a /etc/sks/sksconf
  - sudo /etc/init.d/sks start
  - sudo cat /etc/sks/sksconf
  - make install

script:
  - make test

after_success:
  - make coverage

notifications:
  email:
    on_success: never
