<?php if(($piwik_url=$this->getConfig('piwik_url')) && ($piwik_site=$this->getConfig('piwik_site_id'))): ?>
  <script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="<?php echo $piwik_url; ?>";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '<?php echo $piwik_site; ?>']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
<?php endif; ?>