
      <address>
      <a id="co2" title="Powered with Green Energy" target="_blank" href="//www.dreamhost.com/green.cgi?<?php echo $this->getConfig('hostname') ?>">CO<sub>2</sub> Neutral</a>
      Please send bug reports to
      <a href="mailto:<?php echo $this->getConfig('bugs_contact_mail') ?>">&lt;<?php echo $this->getConfig('bugs_contact_mail') ?>&gt;</a>
      only after reading the <a title="FAQ" href="/doc/faq">FAQ</a>.
      </address>
