  <head>
    <title><?php echo $this->getConfig('html_title'); # -- Frequently Asked Questions ?></title>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <?php if($google_verification=$this->getConfig('google_verification')): ?><meta name="google-site-verification" content="<?php echo $google_verification; ?>" /><?php endif; ?>
  </head>
