<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<?php echo $this->getBlock('head'); ?>
  <body>
    <?php echo $this->getBlock('gnu_inside'); ?>
    <div id="content" style="width:640px;margin:0px auto;">
      <h1 style="margin-bottom:0px;"><?php echo $this->getConfig('html_title') ?></h1>
      <div style="text-align:right;">
        <a title="home" href="/">home</a> | <a title="faq" href="/doc/faq">faq</a> | <a title="stats" href="/pks/lookup?op=stats">stats</a> | <a title="dump" href="/dump">dump</a>
      </div>
      <hr />
      <?php echo $this->getPage(); ?>
      <?php echo $this->getBlock('footer'); ?>
    </div>
  </body>
</html>